### ISSUE TITLE
raw可以考虑改一下cdn源 改成cdn就可以拉取了

### ISSUE THREAD

**Issue by 505737102** [qxzg/Actions#1]
https://cdn.jsdelivr.net/gh/qxzg/Actions@master/fancyss_rules

**Comment by qxzg** [comment]
这个cdn的缓存时间有点长，如果无法拉取的话可以试试fastgit的反代：
https://raw.fastgit.org/qxzg/Actions/master/fancyss_rules

**Comment by qxzg** [comment]
fastgit好像确实不太好使，已更新JsDelivr CDN的说明
