### ISSUE TITLE
已经更新了，可是好像不生效，google 依然在gfwlist 模式下无法访问

### ISSUE THREAD

**Issue by iwaitu** [qxzg/Actions#13]
gfwlist域名数量	5,554 条，版本：2021-09-14
大陆白名单IP段数量	8,615 行，包含 343,942,144 个ip地址，版本：2021-09-16
国内域名数量（cdn名单）	68,162 条，版本：2021-09-14

**Comment by qxzg** [comment]
抱歉，我现在已经不用这个软件了，所以无法解决使用问题
