### ISSUE TITLE
建议大陆白名单更换一个库

### ISSUE THREAD

**Issue by rex5652** [qxzg/Actions#14]
https://ispip.clang.cn/all_cn.txt 的路由没有汇总，总数太多了，
建议更换到这个：https://github.com/misakaio/chnroutes2/blob/master/chnroutes.txt

**Comment by qxzg** [comment]
因为我已经不再使用fancyss，目前没有测试环境，如果您测试过这个列表没问题的话我就直接换了

**Comment by qxzg** [comment]
测试一下，已经改了


>  但是前两行的注释最好能删掉，不知道fancyss的rules文件里有这两行注释会不会有问题

更新脚本默认会删除#开头的行的

**Comment by rex5652** [comment]
可以用了，非常感谢
