### ISSUE TITLE
请问一下，安装了你的脚本之后科学上网那边还需要进行相应的设置吗？

### ISSUE THREAD

**Issue by yimrliu** [qxzg/Actions#17]
很棒的插件！有几个问题想请教一下作者：
1. 似乎科学上网那边设置还是需要打开“定时更新规则任务”吧？我手动运行了一下你的脚本ss_run_update.sh然后给了下面的信息：
![Capture](https://user-images.githubusercontent.com/12740277/166086238-adce16dc-41c0-47ce-92df-107bbe2269ac.PNG)

2. 请问除了1所说的需要勾选外，还需要在科学上网插件中进行其他的设置吗？
3. 是使用"GFWList"还是"大陆白名单模式"？哪个比较好呢？

第一次自己刷机玩这个，所以问题比较多，麻烦作者看看了。谢谢！

**Comment by qxzg** [comment]
1. 都可以，偶尔进去手动更新一下也可以，看个人喜好
2. 我已经很久不使用这个插件了，所以不清楚具体设置
3. 这个也是看个人喜好，区别就是gfwlis只会让被墙的域名走代理，白名单是国外流量全走代理

**Comment by yimrliu** [comment]
好的哈，多谢了。那最近用比较好玩的插件有什么可以推荐的吗？找了几个论坛，都被封了。

**Comment by qxzg** [comment]
https://mcreadme.gitbook.io/mc
这个配置起来更麻烦，但是比较好用

**Comment by yimrliu** [comment]
多谢了。
