### ISSUE TITLE
fancyss 3.0的新规则库已更新，是否可再开一个项目？

### ISSUE THREAD

**Issue by rex5652** [qxzg/Actions#19]
https://github.com/hq450/fancyss/tree/3.0/rules
这是新的规则库，检测版本不再用version1文件做判断，是否可以再开一个项目来跟进？
谢谢。

**Comment by qxzg** [comment]
不好意思，我现在已经不再使用fancyss，所以此项目不会再有更新了

**Comment by liucheng1109** [comment]
好可惜啊。。。以后没法更新了

**Comment by qxzg** [comment]
已更新支持3.0，但是未经测试，如果测试有问题欢迎反馈

**Comment by demonqiqi** [comment]
> 已更新支持3.0，但是未经测试，如果测试有问题欢迎反馈

rules.json.js是空的，更新时提示验证失败

**Comment by qxzg** [comment]
> rules.json.js是空的，更新时提示验证失败

已修复（应该），再试试呢

**Comment by demonqiqi** [comment]
还是有点问题，在rules.json.js里，比如gfwlist.conf和别的一些文件，date和md5与实际不符，导致更新失败。

**Comment by qxzg** [comment]
> 还是有点问题，在rules.json.js里，比如gfwlist.conf和别的一些文档，date和md5与实际不符，导致更新失败。

@demonqiqi 
已修复https://github.com/qxzg/Actions/commit/1122b0ee43ea42e9dc5431003baf5ed9d3e6b3a6

**Comment by demonqiqi** [comment]
已修复，非常感谢

**Comment by liucheng1109** [comment]
项目又启用了么？可以正常使用么？现在fancyss 是3.0.5版本的

**Comment by qxzg** [comment]
> 项目又启用了么？可以正常使用么？现在fancyss 是3.0.5版本的

可以，如果有问题欢迎反馈

**Comment by liucheng1109** [comment]
> 



> 

我执行了，但是更新提示没有新版本。。

**Comment by liucheng1109** [comment]
> > 项目又启用了么？可以正常使用么？现在fancyss 是3.0.5版本的
> 
> 可以，如果有问题欢迎反馈

你好，我执行命令了，更新显示版本相同啊，我需要提供什么日志

<html>
<body>


gfwlist域名数量 | 5,598 条，版本：2022-09-30 09:09
-- | --
4,237 行，包含 265,619,430 个ip地址，版本：2022-09-30 09:09
65,395 条，版本：2022-09-30 09:09


</body>
</html>gfwlist域名数量	5,598 条，版本：[2022-09-30 09:09](https://github.com/hq450/fancyss/blob/3.0/rules/gfwlist.conf)
大陆白名单IP段数量	4,237 行，包含 265,619,430 个ip地址，版本：[2022-09-30 09:09](https://github.com/hq450/fancyss/blob/3.0/rules/chnroute.txt)
国内域名数量（cdn名单）	65,395 条，版本：[2022-09-30 09:09](https://github.com/hq450/fancyss/blob/3.0/rules/cdn.txt)

**Comment by liucheng1109** [comment]
![屏幕截图 2022-10-15 211400](https://user-images.githubusercontent.com/27625516/195988338-e71ec543-f2c6-4072-bbf0-da772a9594ec.jpg)

**Comment by qxzg** [comment]
已更新README https://github.com/qxzg/Actions/commit/238c523a0a4d47136407a80c4b5ab6ab4cce19e3
fancyss 3.0.4更新了变量名，导致老命令失效，你用新的命令试一下

**Comment by liucheng1109** [comment]
> 已更新README [238c523](https://github.com/qxzg/Actions/commit/238c523a0a4d47136407a80c4b5ab6ab4cce19e3) fancyss 3.0.4更新了变量名，导致老命令失效，你用新的命令试一下

新的命令可以用了，已正常更新，我的fancyss是3.0.5.十分感谢
