### ISSUE TITLE
readme里面的介绍似乎有问题

### ISSUE THREAD

**Issue by crazyshitass** [qxzg/Actions#2]
V2RAY应该是替换v2ray_config.sh里面的地址吧？不过我2个都给替换了，更新规则没有成功……

**Comment by qxzg** [comment]
第一个问题：fancyss插件没有v2ray_config.sh这个脚本啊，你用的是那个插件？
第二个问题：规则更新不成功一般是国内dns污染导致你无法连接raw.githubusercontent.com，可以替换成`https://cdn.jsdelivr.net/gh/qxzg/Actions@master/fancyss_rules`试一下，但是这个cdn有缓存，无法做到即时更新

**Comment by crazyshitass** [comment]
> 1. fancyss插件没有v2ray_config.sh这个脚本啊，你用的是那个插件？
> 2. 规则更新不成功一般是国内dns污染导致你无法连接raw.githubusercontent.com，可以替换成`https://cdn.jsdelivr.net/gh/qxzg/Actions@master/fancyss_rules`试一下，但是这个cdn有缓存，无法做到即时更新

环境：LEDE 2.36 ，酷软离线安装的v2ray for openwrt - 2.3.7
再试试

**Comment by qxzg** [comment]
抱歉，我目前没有LEDE环境，所以无法测试。你可以改成大陆白名单或者全局模式试试能不能正常更新

**Comment by crazyshitass** [comment]
> 抱歉，我目前没有LEDE环境，所以无法测试。你可以改成大陆白名单或者全局模式试试能不能正常更新

非常感谢您这块的工作，非常有价值的！我也研究下我自己的环境怎么能够实现更新迁移。

**Comment by qxzg** [comment]
> 非常感谢您这块的工作，非常有价值的！我也研究下我自己的环境怎么能够实现更新迁移。

我刚刚装了一个虚拟机测试了一下，fancyss_x64版本需要在url_main最后加上`/`才可以正常更新
![Snipaste_2021-02-22_17-53-33](https://user-images.githubusercontent.com/30212669/108691960-06a41600-7537-11eb-925c-8ec0fd3bcb37.jpg)
如果还是不行的话说明是你那边网络环境的问题

**Comment by crazyshitass** [comment]
> > 非常感谢您这块的工作，非常有价值的！我也研究下我自己的环境怎么能够实现更新迁移。
> 
> 我刚刚装了一个虚拟机测试了一下，fancyss_x64版本需要在url_main最后加上`/`才可以正常更新
> ![Snipaste_2021-02-22_17-53-33](https://user-images.githubusercontent.com/30212669/108691960-06a41600-7537-11eb-925c-8ec0fd3bcb37.jpg)
> 如果还是不行的话说明是你那边网络环境的问题

非常感谢您的亲自测试！我后面测试发现2点有意思的事，1、直接下载v2ray_config.sh改好后替换源文件，好像不行，会导致程序更新的时候出问题，日志空白，然后一会儿v2ray就掉线，重启也不行，只能恢复备份；2、用ssh命令行形式更改可以，然后用后面您提供的链接完成了更新——https://cdn.jsdelivr.net/gh/qxzg/Actions@master/fancyss_rules，而raw.githubusercontent.com那个更新地址，即便用白名单模式我都没能更新成功。供您调试参考。另外建议在说明文档补充下V2RY的地址更换教程。再次感谢劳动付出：）

**Comment by qxzg** [comment]
x86版本的说明已更新，因为有koolss，v2ray，wireguard，brook一共四个插件，所以就没写具体的文件和位置

**Comment by qxzg** [comment]
> 1、直接下载v2ray_config.sh改好后替换源文件，好像不行，会导致程序更新的时候出问题，日志空白，然后一会儿v2ray就掉线，重启也不行，只能恢复备份，用ssh命令行形式更改可以。

这个一般是文件编码或者权限的问题，建议用Notepad++试一下

> 再次感谢劳动付出：）

不客气，能帮上你们的忙我也很高兴 QwQ
