### ISSUE TITLE
hnd新的3.0.3插件用了这个命令后提示没有检测到在线版本，请问有办法解决吗？

### ISSUE THREAD

**Issue by milaixian111** [qxzg/Actions#21]

**Comment by hedongsheng** [comment]
两条命令都显示同样的提示“没有检测到在线版本，可能是访问github有问题”，可能 是bug

**Comment by qxzg** [comment]
不支持新的3.0版本 #19

**Comment by qxzg** [comment]
已更新支持3.0，但是未经测试，如果测试有问题欢迎到https://github.com/qxzg/Actions/issues/19反馈
