### ISSUE TITLE
这个源是不是不支持新版科学上网了啊。

### ISSUE THREAD

**Issue by liucheng1109** [qxzg/Actions#22]
更新提示

【2022年07月17日 16:39:47】: 应用ss规则定时更新任务：每天4自动检测更新规则.
==================================================================================================
【2022年07月17日 16:39:47】: 开始更新shadowsocks规则，请等待...
【2022年07月17日 16:39:49】: 没有检测到在线版本，可能是访问github有问题，去大陆白名单模式试试吧

**Comment by liucheng1109** [comment]
fancyss插件版本：3.0.3

**Comment by qxzg** [comment]
是的 #19

**Comment by qxzg** [comment]
已更新支持3.0，但是未经测试，如果测试有问题欢迎到 https://github.com/qxzg/Actions/issues/19 反馈
