### ISSUE TITLE
fancyss 旧规则是否还能继续更新啊

### ISSUE THREAD

**Issue by cary-sas** [qxzg/Actions#23]
你好，
才注意到你的项目有了重大更新，我的[项目](https://github.com/cary-sas/v2ray_bin)一直还在用fancyss 的旧规则格式，更新规则的源用的是你的旧规则源，可以帮忙继续更新吗？或者你指导我应该如何自己自动更新啊。

非常感谢！

**Comment by qxzg** [comment]
旧的规则和更新脚本还在master分支里：https://github.com/qxzg/Actions/tree/master
您可以把master分支直接下载下来放到你的repo里，然后开启仓库的actions功能应该就行了

**Comment by qxzg** [comment]
https://github.com/qxzg/Actions/commit/76d8aac7e49cb288cf16302cbfcda36834eaaa25
新增了一个[action](https://github.com/qxzg/Actions/actions/workflows/fancyss-rules-old.yml)，旧的规则会在master分支里继续更新，可以不用更改源地址直可以不用更改源地址直接更新接更新
