### ISSUE TITLE
关于 google China 和 apple China 的疑问

### ISSUE THREAD

**Issue by cary-sas** [qxzg/Actions#24]
想请教一下[google_china.txt](https://github.com/qxzg/Actions/blob/master/fancyss_rules/google_china.txt)， [apple_china.txt](https://github.com/qxzg/Actions/blob/master/fancyss_rules/apple_china.txt) 这两个文件应该怎么使用啊，是把里面的网址放在黑名单里面，然后分流走国外代理吗？

**Comment by qxzg** [comment]
这个不清楚，我已经很久不用fancyss了
