### ISSUE TITLE
OpenAI 显示所在国家不支持

### ISSUE THREAD

**Issue by cary-sas** [qxzg/Actions#25]
I use this project's rule, and whatever applies "Global" or "CHN white list" mode, OpenAI's chartGPT always says "Country does not support", the same proxy node in V2rayN works.
Please help me check, whether openai.com or chart.openai.com are in the foreign rule group.

**Comment by qxzg** [comment]
本项目只是搬运了官方的规则更新脚本，并不会对规则内容进行处理。
对于具体域名的的代理问题请联系上游的chnroutes/gfwlist仓库，或自行解决。
