### ISSUE TITLE
gfwlist停留在1月4日版本一直未更新？

### ISSUE THREAD

**Issue by emule2000** [qxzg/Actions#26]
大陆白名单和CDN名单正常更新分别是2.14与2.13版本。

我看gfwlist/gfwlist已经是2.7版本的样子。

**Comment by qxzg** [comment]
gfwlist源是[Loukky/gfwlist-by-loukky](https://github.com/Loukky/gfwlist-by-loukky)
https://github.com/qxzg/Actions/blob/3.0/fancyss_rules/auto_update/fwlist.py#L27

**Comment by emule2000** [comment]
了解，谢谢解答，[gfwlist-by-loukky](https://github.com/Loukky/gfwlist-by-loukky)该项目更新够慢的……

**Comment by qxzg** [comment]
原项目里就是用的这个源：https://github.com/qxzg/Actions/blob/3.0/fancyss_rules/auto_update/fwlist.py
其实我也不知道为什么2333

**Comment by emule2000** [comment]
qxzg君方便的话可否增加一个你的项目版本把原本的gfwlist源改为[gfwlist/gfwlist](https://github.com/gfwlist/gfwlist)？给我这类代码盲多一个选择:)

**Comment by greed229** [comment]
> 原项目里就是用的这个源：https://github.com/hq450/fancyss/blob/3.0/rules/auto_update/fwlist.py 其实我也不知道为什么2333

更新完提示‘下载完成，但是校验没有通过！’算是成功了吗?

**Comment by si431eb** [comment]
neng yong jiu xing

**Comment by ba80d4b** [comment]
neng yong jiu xing

**Comment by shie12aa14** [comment]
neng yong jiu xing
