### ISSUE TITLE
请问本项目的gfwlist用的是哪个源？  v2ex和docker不在里面

### ISSUE THREAD

**Issue by lxr760** [qxzg/Actions#27]
v2ex.com      docker.com都是被墙网站，但是gfw列表里没有

网上看别的gfwlist里是有这2个网站的

**Comment by qxzg** [comment]
https://github.com/Loukky/gfwlist-by-loukky
具体域名的问题请到这里面提issue

**Comment by lxr760** [comment]
> https://github.com/Loukky/gfwlist-by-loukky 具体域名的问题请到这里面提issue

docker可以访问，但是v2ex还是不能     不知道什么问题      看了loukky的list里面是有v2ex域名的

**Comment by qxzg** [comment]
https://github.com/qxzg/Actions/blob/5d2fadf853bb5d3b3a35800ff7a0c5ad73b478cf/fancyss_rules/auto_update/update_rules.sh#L36
想起来了，是脚本里吧v2ex给手动删掉了

**Comment by qxzg** [comment]
https://github.com/qxzg/Actions/commit/bbf7d32c9a0ea462cf5a5a9fb728c2f93a971a78 已修复，你更新一下试试
