### ISSUE TITLE
校验无法通过

### ISSUE THREAD

**Issue by cranelee** [qxzg/Actions#29]
![image](https://github.com/qxzg/Actions/assets/5615656/36b85d51-10ab-45db-9c5b-0d9b04ac7f37)

**Comment by qxzg** [comment]
你用的是github直连还是jsDelivr CDN？如果是后者的话可能需要等一段时间后重新更新

**Comment by cranelee** [comment]
jsDelivr CDN，改 github后正常，还有fancyss里显示规则条数都是空的

**Comment by qxzg** [comment]
那应该是cdn更新的问题。
还有别人也有类似情况吗，因为我现在不用fancyss了，所以没法测试
