### ISSUE TITLE
discord桌面app沒有被代理

### ISSUE THREAD

**Issue by Lather0519** [qxzg/Actions#30]
以下有些域名沒有被DNS分流，不清楚是哪些
- updates.discord.com:443 
- discord.com:443 
- gateway.discord.gg:443 
- cdn.discordapp.com:443 
- media.discordapp.net:443 
- latency.discord.media:443
- images-ext-1.discordapp.net:443
- i.scdn.co:443 

請問@qxzg 您使用的是哪個源，方便的話是否可以代我提交到源issues
感謝你的項目

**Comment by qxzg** [comment]
https://github.com/Loukky/gfwlist-by-loukky
抱歉回复的不太及时

**Comment by Lather0519** [comment]
> https://github.com/Loukky/gfwlist-by-loukky 抱歉回复的不太及时

我並不是因為這個原因關閉issue，不用介意。

在網路上搜尋了一下discord桌面的影音訊都使用udp傳輸，應該是跟數據傳輸方式有關。
加之很少使用桌面app，所以就不管它了。

感謝回覆。
