### ISSUE TITLE
不会自动更新  设定了凌晨2点更新，硬是没反应

### ISSUE THREAD

**Issue by klcb2010** [qxzg/Actions#31]
图片是我今天才更改的设置 

![截屏图片](https://github.com/qxzg/Actions/assets/32628414/a5fd926d-2774-434e-bc33-fbc5e9ea4be0)

**Comment by qxzg** [comment]
试一下手动更新，看看能不能更新成功呢

**Comment by klcb2010** [comment]
> 试一下手动更新，看看能不能更新成功呢
手动没问题的

**Comment by qxzg** [comment]
手动更新没问题的话，那有可能是软件的定时任务本身出了什么问题。抱歉关于软件本体的问题我无法提供支持（我已经很久不用fancyss了）

**Comment by klcb2010** [comment]
已证实是固件问题  更新cron解决
