### ISSUE TITLE
有没有考虑用0.0.0.0代替127.0.0.0

### ISSUE THREAD

**Issue by klcb2010** [qxzg/Actions#32]
这个仓库的理由 https://github.com/StevenBlack/hosts

![截屏图片 (1)](https://github.com/qxzg/Actions/assets/32628414/0082d0bd-9e47-403a-b95d-ee032922921b)

**Comment by qxzg** [comment]
您能在本地测试一下用 0.0.0.0 代替 127.0.0.0 之后功能是否正常吗，如果没问题的话我来改一下

**Comment by klcb2010** [comment]
> 您能在本地测试一下用 0.0.0.0 代替 127.0.0.0 之后功能是否正常吗，如果没问题的话我来改一下

![截屏图片](https://github.com/qxzg/Actions/assets/32628414/e4936fb1-070e-48eb-b10c-1ef7e0fdc534)
看起来没问题

**Comment by qxzg** [comment]
我看binmt.cc是保存在[cdn.txt](https://github.com/qxzg/Actions/blob/3.0/fancyss_rules/cdn.txt)中的，这个文件里不保存地址，而且这里的域名应该不是需要屏蔽的吧。

没太理解您说的是什么意思，我看只有[gfwlist.conf](https://github.com/qxzg/Actions/blob/3.0/fancyss_rules/gfwlist.conf)里有 127.0.0.0

**Comment by qxzg** [comment]
已经在https://github.com/qxzg/Actions/tree/tset分支更新了0.0.0.0版本的gfwlist，可以测试一下

**Comment by klcb2010** [comment]
这个替换规则 链接我不会写 😂

**Comment by qxzg** [comment]
使用`vi /koolshare/scripts/ss_rule_update.sh`编辑ss_rule_update.sh文件的第9行，改为`URL_MAIN="https://raw.githubusercontent.com/qxzg/Actions/tset/fancyss_rules"`

**Comment by klcb2010** [comment]
设置好了  明天早上看效果

**Comment by klcb2010** [comment]
> 使用`vi /koolshare/scripts/ss_rule_update.sh`命令编辑ss_rule_update.sh文件，把第9行改为`URL_MAIN="https://raw.githubusercontent.com/qxzg/Actions/tset/fancyss_rules"`

测试没问题
