### ISSUE TITLE
大陆白名单模式出现双×且无法上网

### ISSUE THREAD

**Issue by FlameMida** [qxzg/Actions#4]
![image](https://user-images.githubusercontent.com/33086993/113504642-f9356f00-956b-11eb-8e1f-29ca6f042740.png)
经测试发现使用了4月4日这个规则后，大陆白名单模式无法正常上网。gfwlist模式正常。
卸载插件重装后使用大陆白名单正常，替换后又出现大陆白名单无法上网
AC-86u 386.1_2

**Comment by qxzg** [comment]
我自己用的也是大陆白名单(ax86u 386.1_2)，目前没有发现问题
是4号的规则更新之后才出现的问题吗，之前能不能正常使用
![Snipaste_2021-04-04_18-01-18](https://user-images.githubusercontent.com/30212669/113505170-c42b1b80-956f-11eb-8fb0-8e779d6d545a.jpg)

**Comment by FlameMida** [comment]
之前是正常的，今天起来就这样了...然后试了一个早上

**Comment by qxzg** [comment]
请重新更新一下规则，是问题是由于[felixonmars/dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)添加了一个没有编码的中文域名导致dnsmasq 启动失败
现在已经移除掉了

**Comment by FlameMida** [comment]
OK，谢谢大佬
