### ISSUE TITLE
CDN文件校验不不通过

### ISSUE THREAD

**Issue by sumic** [qxzg/Actions#8]
【2021年05月17日 12:57:53】: 检测到新版本cdn名单，开始更新...
【2021年05月17日 12:57:53】: 下载cdn名单到临时文件...
【2021年05月17日 12:57:54】: 下载完成，但是校验没有通过！

**Comment by qxzg** [comment]
jsDelivr CDN的缓存的锅，一些文件更新不及时导致的，目前我也无能为力。
还请尽量使用GitHub直链，或者过段时间再试

**Comment by CurtisWong458** [comment]
> jsDelivr CDN的缓存的锅，一些文件更新不及时导致的，目前我也无能为力。
> 还请尽量使用GitHub直链，或者过段时间再试

大佬想问一下，使用的是GitHub直链以前都可以正常更新规则，最近几天发现不自动更新规则了（设置的4点更新）

**Comment by qxzg** [comment]
> 大佬想问一下，使用的是GitHub直链以前都可以正常更新规则，最近几天发现不自动更新规则了（设置的4点更新）

手动更新试一下，如果没问题的话就重新保存一下定时更新任务

**Comment by CurtisWong458** [comment]
> > 大佬想问一下，使用的是GitHub直链以前都可以正常更新规则，最近几天发现不自动更新规则了（设置的4点更新）
> 
> 手动更新试一下，如果没问题的话就重新保存一下定时更新任务

手动更新可以的，但是就不能自动更新咋回事啊

**Comment by qxzg** [comment]
> 手动更新可以的，但是就不能自动更新咋回事啊

那我就不太清楚了，不好意思帮不上你
