### ISSUE TITLE
使用 FastGit 来下载文件

### ISSUE THREAD

**Issue by MidAutumnMoon** [qxzg/Actions#9]
https://doc.fastgit.org/ 提供了 GitHub 的反代，速度快又不会像 jsDelivr 那样有更新延迟，希望能试一试。

**Comment by qxzg** [comment]
抱歉这么久都没回复，因为我已经不再使用Fancyss，所以没有测试环境。如果您测试可以用的话可以开pr

**Comment by MidAutumnMoon** [comment]
了解了，不过我最近换了其他方法，所以也不再用 fancyss 了。
